CREATE TABLE encomendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_destinatario VARCHAR(150) NOT NULL,
  apartamento VARCHAR(20) NOT NULL,
  bloco VARCHAR(20) NOT NULL,
  descricao VARCHAR(500) NOT NULL,
  recebido_por VARCHAR(120) NOT NULL,
  status VARCHAR(20) NOT NULL,
  data_recebimento TIMESTAMP WITH TIME ZONE NOT NULL,
  data_retirada TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_encomendas_status ON encomendas(status);
