CREATE TABLE encomendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_destinatario VARCHAR(150) NOT NULL,
  apartamento VARCHAR(20) NOT NULL,
  bloco VARCHAR(20) NOT NULL,
  descricao VARCHAR(500) NOT NULL,
  recebido_por VARCHAR(120) NOT NULL,
  status VARCHAR(20) NOT NULL,
  data_recebimento TIMESTAMP WITH TIME ZONE NOT NULL,
  data_retirada TIMESTAMP WITH TIME ZONE,
  retirado_por_nome VARCHAR(150)
);

CREATE INDEX idx_encomendas_status ON encomendas(status);

CREATE TABLE outbox_event (
  id VARCHAR(36) PRIMARY KEY,
  aggregatetype VARCHAR(100) NOT NULL,
  aggregateid VARCHAR(100) NOT NULL,
  type VARCHAR(120) NOT NULL,
  event_version INTEGER NOT NULL,
  payload TEXT NOT NULL,
  event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
  event_timestamp_ms BIGINT NOT NULL
);

CREATE INDEX idx_outbox_aggregate ON outbox_event(aggregatetype, aggregateid);
CREATE INDEX idx_outbox_timestamp ON outbox_event(event_timestamp);
CREATE INDEX idx_outbox_timestamp_ms ON outbox_event(event_timestamp_ms);
